/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.AdminRole;
import Backend.EmployeeUser;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class AdminRoleWindow extends javax.swing.JFrame implements Node {

    /**
     * Creates new form AdminRoleWindow
     */
    private Node parent;
    AddEmployeeWindow  addEmployeeWindow;
    ViewEmployeesWindow  viewEmployeesWindow;
    RemoveEmployeeWindow  removeEmployeeWindow;
    AdminRole adminRole;
    public AdminRoleWindow() {
        initComponents();
        adminRole=new AdminRole();
        addEmployeeWindow=new AddEmployeeWindow(adminRole);
        addEmployeeWindow.setParentNode(this);
        addEmployeeWindow.setVisible(false);
        
        viewEmployeesWindow=null;
       
        
        removeEmployeeWindow=new RemoveEmployeeWindow(adminRole);
        removeEmployeeWindow.setParentNode(this);
        
        
    }
    public String STRING(String a,String b,String c,String d,String e)
        {
            String s=a+","+b+","+c+","+d+","+e;
            return s;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmployee = new javax.swing.JButton();
        viewEmployees = new javax.swing.JButton();
        removeEmployee = new javax.swing.JButton();
        LogoutAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addEmployee.setBackground(new java.awt.Color(0, 0, 0));
        addEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        addEmployee.setText("Add Employee");
        addEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        viewEmployees.setBackground(new java.awt.Color(0, 0, 0));
        viewEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewEmployees.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployees.setText("View Employees");
        viewEmployees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesActionPerformed(evt);
            }
        });

        removeEmployee.setBackground(new java.awt.Color(0, 0, 0));
        removeEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeEmployee.setForeground(new java.awt.Color(255, 255, 255));
        removeEmployee.setText("Remove Employee");
        removeEmployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeActionPerformed(evt);
            }
        });

        LogoutAdmin.setBackground(new java.awt.Color(0, 0, 0));
        LogoutAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogoutAdmin.setForeground(new java.awt.Color(255, 255, 255));
        LogoutAdmin.setText("Logout");
        LogoutAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(LogoutAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);   
         //AddEmployeeWindow addEmployeeWindow =new AddEmployeeWindow(adminRole);
        addEmployeeWindow.setVisible(true);
        
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void removeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);    
        
        removeEmployeeWindow.setVisible(true);
    }//GEN-LAST:event_removeEmployeeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "If you want to exit this Window,you need to LOGOUT");

    }//GEN-LAST:event_formWindowClosing

    
    private void viewEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesActionPerformed
        // TODO add your handling code here:
    if(viewEmployeesWindow==null)
        {
            viewEmployeesWindow=new ViewEmployeesWindow(new String[]{"Employee ID","Name","Email","Address","PhoneNumber"});
        }
         viewEmployeesWindow.setParentNode(this);
        this.setVisible(false);
        viewEmployeesWindow.setVisible(true);
        
        EmployeeUser E[]=addEmployeeWindow.adminRole.getListOfEmployees();
       
        String[][]tableData= new String[E.length][5];
        for(int i=0;i<E.length;i++)
        {
            String sr= STRING(E[i].getEmployeeID(),E[i].getName(),E[i].getEmail(),E[i].getAddress(),E[i].getPhoneNumber());
            tableData[i]=sr.split(",");
           
        }
       
        viewEmployeesWindow.setData(tableData);
        viewEmployeesWindow.setTitle("View Product");

    }//GEN-LAST:event_viewEmployeesActionPerformed

    private void LogoutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutAdminActionPerformed
        try {
            // TODO add your handling code here:
            adminRole.logout();
        } catch (IOException ex) {
            Logger.getLogger(AdminRoleWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        ((JFrame)this.getParentNode().getParentNode()).setVisible(true);
        
    }//GEN-LAST:event_LogoutAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutAdmin;
    private javax.swing.JButton addEmployee;
    private javax.swing.JButton removeEmployee;
    private javax.swing.JButton viewEmployees;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent=node;
    }
}
